/** Layout PCPA132I.DAT — baixa por operação (PC1132) */
import type { LayoutRegistro } from '../parse-dat';

export const LAYOUT_PCPA132I: LayoutRegistro = {
  nomeArquivo: 'PCPA132I.DAT',
  tamanhoRegistro: 194,
  campos: [
    { nome: 'codigoOp', tipo: 'numerico', tamanho: 8 },
    { nome: 'numeroOperacao', tipo: 'numerico', tamanho: 2 },
    { nome: 'spaces', tipo: 'texto', tamanho: 2 },
    { nome: 'anoLcto', tipo: 'numerico', tamanho: 4 },
    { nome: 'mesLcto', tipo: 'numerico', tamanho: 2 },
    { nome: 'diaLcto', tipo: 'numerico', tamanho: 2 },
    { nome: 'anoIni', tipo: 'numerico', tamanho: 4 },
    { nome: 'mesIni', tipo: 'numerico', tamanho: 2 },
    { nome: 'diaIni', tipo: 'numerico', tamanho: 2 },
    { nome: 'horaIniHh', tipo: 'numerico', tamanho: 2 },
    { nome: 'horaIniMm', tipo: 'numerico', tamanho: 2 },
    { nome: 'horaIniSs', tipo: 'numerico', tamanho: 2 },
    { nome: 'anoFim', tipo: 'numerico', tamanho: 4 },
    { nome: 'mesFim', tipo: 'numerico', tamanho: 2 },
    { nome: 'diaFim', tipo: 'numerico', tamanho: 2 },
    { nome: 'horaFimHh', tipo: 'numerico', tamanho: 2 },
    { nome: 'horaFimMm', tipo: 'numerico', tamanho: 2 },
    { nome: 'horaFimSs', tipo: 'numerico', tamanho: 2 },
    { nome: 'diasTotal', tipo: 'numerico', tamanho: 3 },
    { nome: 'tempoTotalHh', tipo: 'numerico', tamanho: 2 },
    { nome: 'tempoTotalMm', tipo: 'numerico', tamanho: 2 },
    { nome: 'tempoTotalSs', tipo: 'numerico', tamanho: 2 },
    { nome: 'equipamentoGrupo', tipo: 'numerico', tamanho: 2 },
    { nome: 'equipamentoCodigo', tipo: 'numerico', tamanho: 4 },
    { nome: 'qtdeSaida', tipo: 'numerico', tamanho: 6 },
    { nome: 'pesoSaidaInt', tipo: 'numerico', tamanho: 6 },
    { nome: 'pesoSaidaDec', tipo: 'numerico', tamanho: 2 },
    { nome: 'anoSaida', tipo: 'numerico', tamanho: 4 },
    { nome: 'mesSaida', tipo: 'numerico', tamanho: 2 },
    { nome: 'diaSaida', tipo: 'numerico', tamanho: 2 },
    { nome: 'qtdeEntrada', tipo: 'numerico', tamanho: 6 },
    { nome: 'pesoEntradaInt', tipo: 'numerico', tamanho: 6 },
    { nome: 'pesoEntradaDec', tipo: 'numerico', tamanho: 2 },
    { nome: 'anoEntrada', tipo: 'numerico', tamanho: 4 },
    { nome: 'mesEntrada', tipo: 'numerico', tamanho: 2 },
    { nome: 'diaEntrada', tipo: 'numerico', tamanho: 2 },
    { nome: 'diferQtde', tipo: 'numerico', tamanho: 6 },
    { nome: 'diferPesoInt', tipo: 'numerico', tamanho: 6 },
    { nome: 'diferPesoDec', tipo: 'numerico', tamanho: 2 },
    { nome: 'diferTempo', tipo: 'numerico', tamanho: 3 },
    { nome: 'atualizouEstoque', tipo: 'texto', tamanho: 1 },
    { nome: 'filler', tipo: 'texto', tamanho: 75 },
  ],
};
